- hosts: all
  tasks:
  - name: "Config sshd"
    lineinfile:
      path: "/etc/ssh/sshd_config"
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - {regexp: '^\s*ClientAliveInterval\s+', line: 'ClientAliveInterval 120'}
      - {regexp: '^\s*ClientAliveCountMax\s+', line: 'ClientAliveCountMax 720'}
      - {regexp: '^\s*GSSAPIAuthentication\s+', line: 'GSSAPIAuthentication no'}
      - {regexp: '^\s*UseDNS\s+', line: 'UseDNS no'}
    become: yes

  - name: "Restart sshd"
    systemd:
      state: restarted
      daemon_reload: yes
      name: sshd
    become: yes
